name: Melanie Baljko
bio: my bio
avatar: ./avatar.png

links:
  - name: GitHub
    icon: github
    url: https://mbaljko.github.io/my-quartz/
  - name: Twitter
    icon: twitter
    url: https://twitter.com/yourhandle

# Optional extras
location: Toronto, Canada
theme:
  accentColor: indigo
